### ISSUE TITLE
Notes in Connections

### ISSUE THREAD

**Issue by JDommi** [tardezyx/tar.IMDbScraper#1]
Bei den Connections scheint noch ein Fehler drin zu sein: Die Notes werden nicht übernommen. Auch beim Debuggen ist x.Notes immer null.
Ergebnis:
---Connections Features
https://www.imdb.com/title/tt0679174|Arrival (1967) Fernsehepisode Nummer 6 *
```
private static StringBuilder ParseConnections(List<Connection>? connections, bool withNote = false)
        {
            StringBuilder result = new();

            connections?
              .Do(x => result.AppendLine(
                $"{x.AssociatedTitle?.URL}|{x.AssociatedTitle?.LocalizedTitle} ({x.AssociatedTitle?.YearFrom}) {x.AssociatedTitle?.Type} {x.AssociatedTitle?.Series?.LocalizedTitle}"
                + (withNote
                  ? " * " + x.Notes
                  : string.Empty)
              ));

            return result;
        }
```

**Comment by tardezyx** [comment]
Fixed in [v1.1.2](https://github.com/tardezyx/tar.IMDbScraper/releases/tag/1.1.2)

`Connection.Notes` are now type `Text` (which consists of `HtmlText` and `PlainText`).

Example:

```
var allConnections = await Scraper.ScrapeAllConnectionsAsync("tt0679174");

StringBuilder sb = new();

if (allConnections != null) {
  foreach (var item in allConnections.FeaturedIn) {
    sb.AppendLine(
      string.Format(
        "{0}|{1} ({2}) {3} {4} {5}",
        item.AssociatedTitle?.URL,
        item.AssociatedTitle?.LocalizedTitle,
        item.AssociatedTitle?.YearFrom,
        item.AssociatedTitle?.Type,
        item.AssociatedTitle?.Series?.LocalizedTitle,
        item.Notes?.PlainText
      )
    );
  }
}

string result = sb.ToString();
```

**Comment by JDommi** [comment]
At first thanks for fixing!

But why do I get now 31 errors on loading the Exporter?
And where is it in the new v1.1.2?

**Comment by tardezyx** [comment]
The exporter is not part of this project and just an example of how to use the scraper. In order to apply the update, just use the updated nuget package or manually replace the .dll(s) in the exporters folder with the new one(s). Then adjust your code accordingly.

While developing, you could also work with the source code directly by connecting both projects in your IDE (like Visual Studio):

1. add both projects to one solution
2. reference this project to the explorers project (thereby you can (or even should, to prevent double referencing?) remove the .dll reference)
3. For release (when you finished the first releasable version of your app, e.g. such exporter), you need to remove the project reference and add the .dll (again).

It is [also possible to reference both](https://stackoverflow.com/a/45010193/12622162), the project and the .dll (or even better here: the nuget package), depending if you are in debug or release mode. Be aware, that you probably have to edit your .csproj file manually after each update.

Tell me, when it works so that I can close this issue.

**Comment by JDommi** [comment]
You can close it!

Everything works fine now 😃

**Comment by tardezyx** [comment]
Nice!
