### ISSUE TITLE
Missing Connection Category

### ISSUE THREAD

**Issue by JDommi** [tardezyx/tar.IMDbScraper#2]
You have forgotten the connection category Spoofs

Example movie: Der Schuh des Manitu

**Comment by tardezyx** [comment]
Fixed in [v1.2.1](https://github.com/tardezyx/tar.IMDbScraper/releases/tag/1.2.1). You can also check the reworked tar.IMDbExporter in the corresponding [.zip file](https://github.com/tardezyx/tar.IMDbScraper/releases/download/1.2.1/tar.IMDbExporter.zip). Be aware, that you maybe have to rearrange the parsing in `Operator.Parse()` as I changed it alphabetically.

**Comment by JDommi** [comment]
Approved 👍 👍 👍
