### ISSUE TITLE
Latest IMDB changes

### ISSUE THREAD

**Issue by JDommi** [tardezyx/tar.IMDbScraper#4]
Well, since January the Scraper doesn't work anymore :(

**Comment by tardezyx** [comment]
Fixed in [v1.3.2](https://github.com/tardezyx/tar.IMDbScraper/releases/tag/1.3.2).

If it fails to work again: you need to manually update the hash values in [Base/Dict.cs](https://github.com/tardezyx/tar.IMDbScraper/blob/main/tar.IMDbScraper/Base/Dict.cs) according to [this manual](https://github.com/tardezyx/tar.IMDbScraper/blob/main/tar.IMDbScraper/_notes.cs).

If I have enough time, I will look into how this annoying step could be implemented. Until then there is no other workaround.

**Comment by tardezyx** [comment]
Fixed once and for all in [v2.0.0](https://github.com/tardezyx/tar.IMDbScraper/releases/tag/2.0.0). Check [tar.IMDbExporter](https://github.com/tardezyx/tar.IMDbExporter) project and its release(s) for the updated usage.
